name: Keep Web Service Awake_TO_DO
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request
        run: curl -I https://list-your-favor.onrender.com/
